# Generated by Django 5.0.3 on 2026-01-27 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="employee_code",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the employee (e.g., EMP001).",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Employee Code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Restaurant Manager"),
                    ("CASHIER", "Cashier"),
                    ("KITCHEN", "Kitchen Crew"),
                    ("INVENTORY", "Inventory Manager"),
                    ("ADMIN", "System Admin"),
                ],
                default="CASHIER",
                help_text="Designates the role of the user in the restaurant workflow.",
                max_length=50,
                verbose_name="System Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
