# Generated by Django 5.0.3 on 2026-01-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_user_employee_code_user_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        help_text="Name of the settings group",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this group controls",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting Group",
                "verbose_name_plural": "Setting Groups",
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "setting_key",
                    models.CharField(
                        help_text="Unique key for the setting (e.g., 'TAX_RATE')",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("setting_value", models.TextField(help_text="Value stored as text")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        help_text="Data type for type casting",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this setting currently applied?"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group this setting belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="core.settinggroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
