# Generated by Django 5.0.3 on 2026-01-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit for internal management",
                        max_length=100,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Ingredient Name"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g., kg, liter, piece",
                        max_length=50,
                        null=True,
                        verbose_name="Unit of Measure",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cost price per unit of measure",
                        max_digits=10,
                        verbose_name="Cost Per Unit",
                    ),
                ),
                (
                    "alert_threshold",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum stock level to trigger low stock warning",
                        verbose_name="Alert Threshold",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "db_table": "ingredients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "ingredient",
                    models.OneToOneField(
                        db_column="itemId",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="inventory_stock",
                        serialize=False,
                        to="inventory.ingredient",
                        verbose_name="Ingredient",
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Quantity On Hand",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location in the warehouse/kitchen",
                        max_length=255,
                        null=True,
                        verbose_name="Storage Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "db_table": "inventory_items",
            },
        ),
    ]
