# Generated by Django 5.0.3 on 2026-01-27 17:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTakeTicket",
            fields=[
                (
                    "ticket_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Human readable code, e.g., ST-20231027-001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "variance_total_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who initiated the stock take",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_take_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Take Ticket",
                "verbose_name_plural": "Stock Take Tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTakeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Theoretical quantity in system at the time of ticket creation",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_take_history",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="inventory.stocktaketicket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Take Detail",
                "verbose_name_plural": "Stock Take Details",
                "unique_together": {("ticket", "ingredient")},
            },
        ),
    ]
