# Generated by Django 5.0.3 on 2026-01-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0003_recipe_recipeingredient"),
        ("sales", "0005_order_external_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReasonCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the reason (e.g., BURN, EXPIRED).",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the reason."),
                ),
            ],
            options={
                "verbose_name": "Reason Code",
                "verbose_name_plural": "Reason Codes",
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "old_status",
                    models.CharField(
                        help_text="Status before the change.", max_length=50
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        help_text="Status after the change.", max_length=50
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the status change."
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the status change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_detail",
                    models.ForeignKey(
                        help_text="The specific line item in an order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="sales.orderdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="WasteReport",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity wasted.", max_digits=10
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the report was created.",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The user (Kitchen Staff) reporting the waste.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="The menu item being discarded.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_reports",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        help_text="Standardized reason for the waste.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_reports",
                        to="kitchen.reasoncode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Report",
                "verbose_name_plural": "Waste Reports",
                "ordering": ["-reported_at"],
            },
        ),
    ]
