# Generated by Django 5.0.3 on 2026-01-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wastereport",
            name="menu_item",
        ),
        migrations.AddField(
            model_name="wastereport",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wastereport",
            name="loss_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Calculated financial loss.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="wastereport",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
