# Generated by Django 5.0.3 on 2026-01-27 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Display Price"
            ),
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Selling Price"
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Effective Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_history",
                        to="menu.menuitem",
                        verbose_name="Menu Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing",
                "verbose_name_plural": "Pricing History",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["menu_item", "effective_date"],
                        name="menu_pricin_menu_it_1eb111_idx",
                    )
                ],
            },
        ),
    ]
