# Generated by Django 5.0.3 on 2026-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_recipe_recipeingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_popular",
            field=models.BooleanField(
                default=False,
                help_text="Highlight this item in the menu.",
                verbose_name="Is Popular?",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="prep_time",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Estimated time to prepare this dish.",
                verbose_name="Prep Time (mins)",
            ),
        ),
    ]
