# Generated by Django 5.0.3 on 2026-01-28 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_is_popular_menuitem_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_combo',
            field=models.BooleanField(default=False, help_text='Mark this menu item as a combo that groups multiple other items.', verbose_name='Is Combo?'),
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many of this item are included in the combo.', verbose_name='Quantity in Combo')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_components', to='menu.menuitem', verbose_name='Combo Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_of_combos', to='menu.menuitem', verbose_name='Component Item')),
            ],
            options={
                'verbose_name': 'Combo Component',
                'verbose_name_plural': 'Combo Components',
                'unique_together': {('combo', 'item')},
            },
        ),
    ]
