"""
Django settings for fami_project project.

Generated by 'django-admin startproject' using Django 5.x.

This configuration includes:
1. Environment variable loading via django-environ.
2. Custom User Model configuration (core.User).
3. Logging configuration (File & Console).
4. Static & Media file setup.
5. Django Rest Framework setup.
6. CORS headers setup.
"""

import os
from pathlib import Path
import environ  # type: ignore

# 1. Initialize Environment Variables
# ------------------------------------------------------------------------------
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# 2. Core Security Settings
# ------------------------------------------------------------------------------
SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '0.0.0.0', 
    'testserver',
    'sudden-petroleum-stanley-rim.trycloudflare.com', # Thêm dòng này
]

# 1. Thêm domain của Cloudflare vào danh sách tin cậy cho CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://sudden-petroleum-stanley-rim.trycloudflare.com',
]

# 2. Đảm bảo Django hiểu rằng request đang đến qua một proxy an toàn (HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# 3. Application Definition
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-Party Apps
    'rest_framework',
    'corsheaders',

    # Local Project Apps (Modular Monolith Structure)
    'core.apps.CoreConfig',
    'inventory.apps.InventoryConfig',
    'menu.apps.MenuConfig',
    'sales.apps.SalesConfig',
    'kitchen.apps.KitchenConfig',
    'reporting.apps.ReportingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Added for API support
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fami_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fami_project.wsgi.application'
ASGI_APPLICATION = 'fami_project.asgi.application'

# Channels Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}



# 4. Database Configuration
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': env.db_url('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# 5. Password Validation
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 6. Internationalization
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = env('LANGUAGE_CODE', default='en-us')

TIME_ZONE = env('TIME_ZONE', default='Asia/Ho_Chi_Minh')

USE_I18N = True

USE_TZ = True


# 7. Static and Media Files
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Redirect to home URL after login (Default behavior if next is not provided)
LOGIN_REDIRECT_URL = 'core:dashboard'

# Redirect to login page after logout
LOGOUT_REDIRECT_URL = 'core:login'

# URL to redirect to if user is not logged in and tries to access protected page
LOGIN_URL = 'core:login'


# 8. Default Primary Key Field Type
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 9. Custom User Model
# ------------------------------------------------------------------------------
# We point to the core app's User model for RBAC
AUTH_USER_MODEL = 'core.User'


# 10. Rest Framework Configuration
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# 11. CORS Configuration
# ------------------------------------------------------------------------------
# For development, allow all. In production, list specific origins.
CORS_ALLOW_ALL_ORIGINS = DEBUG


# 12. Logging Configuration
# ------------------------------------------------------------------------------
# Logs to console and to a file in the /logs directory
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'fami.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # Add other app loggers here as needed
    },
}
