# Generated by Django 5.0.3 on 2026-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantTable",
            fields=[
                (
                    "table_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Table ID"
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="E.g., T-01, VIP-02",
                        max_length=50,
                        unique=True,
                        verbose_name="Table Name",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Maximum number of guests",
                        verbose_name="Seating Capacity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("DIRTY", "Dirty"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Current Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Restaurant Table",
                "verbose_name_plural": "Restaurant Tables",
                "ordering": ["table_name"],
            },
        ),
    ]
