# Generated by Django 5.0.3 on 2026-01-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_recipe_recipeingredient"),
        ("sales", "0003_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of items ordered."
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per item at the moment of ordering.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated subtotal (Quantity * Unit Price).",
                        max_digits=10,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Special instructions (e.g., 'No onions', 'Extra spicy').",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="The specific dish properly ordered.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_details",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The parent order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="sales.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Order Details",
            },
        ),
    ]
