# Generated by Django 5.0.3 on 2026-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_orderdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="External System ID for idempotent creation.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
