# Generated by Django 5.0.3 on 2026-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_order_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cooking", "Cooking"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                help_text="Status of this specific item.",
                max_length=50,
            ),
        ),
    ]
