# Generated by Django 5.0.3 on 2026-01-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_orderdetail_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when invoice was generated.",
                    ),
                ),
                (
                    "final_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final payable amount after taxes/discounts.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="CASH",
                        help_text="Primary method of payment.",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="The finalized order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="sales.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid in this transaction.",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CARD", "Card"), ("QR", "QR Code")],
                        default="CASH",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="External reference (e.g., Bank Ref).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order being paid for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="sales.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
