# Generated by Django 5.0.3 on 2026-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_invoice_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cooking", "Cooking"),
                    ("Ready", "Ready"),
                    ("Served", "Served"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                help_text="Current processing status of the order.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cooking", "Cooking"),
                    ("Ready", "Ready"),
                    ("Served", "Served"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                help_text="Status of this specific item.",
                max_length=50,
            ),
        ),
    ]
