# Generated by Django 5.0.3 on 2026-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_order_status_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang chọn (Pending)'), ('Cooking', 'Đang chế biến'), ('Ready', 'Sẵn sàng'), ('Served', 'Đã phục vụ'), ('Paid', 'Đã thanh toán'), ('Cancelled', 'Đã hủy')], default='Pending', help_text='Current processing status of the order.', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang chọn (Pending)'), ('Cooking', 'Đang chế biến'), ('Ready', 'Sẵn sàng'), ('Served', 'Đã phục vụ'), ('Paid', 'Đã thanh toán'), ('Cancelled', 'Đã hủy')], default='Pending', help_text='Status of this specific item.', max_length=50),
        ),
    ]
