# Generated by Django 5.0.3 on 2026-01-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_alter_order_status_alter_orderdetail_status"),
        ("sales", "0010_alter_order_status_alter_orderdetail_status"),
    ]

    operations = []
